spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true

novabank:
  kafka:
    topics:
      transfer-requested: bank.transfers.requested